### ISSUE TITLE
Port/Copy C++ files to Github repository

### ISSUE THREAD

**Issue by paulvxx** [cs481-ekh/s24-meshers#22]
References #18  

- [] Simply port over the C++ files from https://github.com/gradywright/mgm over to the current repository.

**Comment by seanbsu** [comment]
- copying c++ files from the original mgm repository to their corresponding locations in this repo.
- looked at the coarsen files and noticed that they are what's linking the original matlab and c++ together by creating the mex files
- will need to be refactored in a future sprint to work with python
[t:30]
