### ISSUE TITLE
Bind and test C++ Libraries in Python

### ISSUE THREAD

**Issue by paulvxx** [cs481-ekh/s24-meshers#25]
References #18 

- [x] Find a python package which is capable of binding C++ libraries into python and calling C++ functions within python
- [x] Test the functionality of the C++ procedures within a python programs (under tests)
Note: If C++ functions/libraries are too complex to test individually, simply make a sample C++ function and test it within a sample python program

**Comment by WorkGitAccount** [comment]
Could create a python extension module using Python C API to bind C++ classes to Python. 

A possibly simpler approach is to use pyBind package to link and bind C++ classes to Python.

**Comment by WorkGitAccount** [comment]
Decided on using pyBind. Worked with Sean to get my environment set up and the current build working. 

[t:30]

**Comment by WorkGitAccount** [comment]
Attempted to use pybind11 by creating a bindings.c++ file that binds C++ class and their functions to python. The steps to bind:
1. Create python bind in file bindings.c++ with pybind11. Define the binding to the constructor 
2. Build the module (cyCodeBase) using C++ compiler with pybind11 header with g++
3. Use the module in python. Import module, create object using imported module and call constructor.

In the first step, for every function need to create a pybind_module definition for that function. There are dozens of functions inside lots of C++ files so this might not be practical.  Consider only binding a select few function such as the constructor.  

Calling just the constructor is how the matlab code implements this:
1. mex compiles and links source files into shared library (cyCodeBase)
2. call PcCoarsen constructor (in a for loop over each level) that calls wse.Eliminate and returns the next level of points x{j} coarsened.  


[t:120]

**Comment by WorkGitAccount** [comment]
Made some edits in C++ but got errors. Researched C++ syntax walked through more code

[t:60]

**Comment by paulvxx** [comment]
- Pair programmed with Tanner
- Discussed some issues with the current C++ implementation of a function, and py binding 

[t:110]

**Comment by WorkGitAccount** [comment]
Pair programming discussed how PcCoarsen2D.cpp uses overloaded operator() with input/output parameter lists shared with matlab. 

Started rewriting the class. Can just define our own input and output parameters. With 2D can make some assumptions and hardcode so only need two input parameters. Discussed data types and C++ conventions.

[t:165]

**Comment by WorkGitAccount** [comment]
Verified build and compilation with new pybind dependencies. Reviewed Docker build settings and how to compile for the container. 

[t:60]

**Comment by WorkGitAccount** [comment]
Working to finish the PcCoarsen2d.cpp rewrite. 

[t:30]

**Comment by WorkGitAccount** [comment]
2nd draft with checkarguments handled in modified Coarsen() function. More edge cases could be handled. Updated data types and added parameters. 

[t:115]

**Comment by WorkGitAccount** [comment]
Another rewrite. Removed most error handling and some data type conversions since this can be done in python. Now a much simpler implementation with better documentation. 

[t:95]

**Comment by WorkGitAccount** [comment]
New bindings and dependencies altered. Fix calling of library. Updated run scripts.

[t:115]

**Comment by WorkGitAccount** [comment]
Reverted some changes. Creation of cy.Point2D better handled in coarsen() function.

[t:135]
