### ISSUE TITLE
Find suitable data structures to manage and manipulate Points (Point Clouds)

### ISSUE THREAD

**Issue by paulvxx** [cs481-ekh/s24-meshers#27]
References #16 

- [x] I need a convenient data structure that can be used to represent points on a graph (find some library to support this if needed)
- [x] The data structures should be easily compatible to work with C++ libraries
- [x] The data structure should be comparable to what is used in Matlab

**Comment by WorkGitAccount** [comment]
The existing cyPackage contains a PointCloud class at /utils/cyCodeBase/cyPointCloud.h  that is suitable as a data structure for a point cloud. 

To manipulate the points, the class at /utils/PcCoarsen2D.cpp is used to coarsen a 2D point cloud. 

Still need to link and test these classes corresponding with issue #25 and issue #30 

[t:30]
