### ISSUE TITLE
Find suitable data structures to manage and manipulate Systems Linear of Equations

### ISSUE THREAD

**Issue by paulvxx** [cs481-ekh/s24-meshers#28]
References #16 

- [x] I need a convenient data structure that can be used to represent systems of linear equations and their solutions
- [x] The data structures should be easily compatible to work with C++ libraries
- [x] The data structure should be comparable to what is used in Matlab

**Comment by WorkGitAccount** [comment]
Dr Grady Wright in our meeting mentioned NumPy as a python library that can handle matrices and matrix operations. It has a System of linear equation backsolver just like Matlab. 

Documentation and install instructions at [numpy.org](numpy.org)

Will still need to bind and test this NumPy library with issue #25

[t:30]
